#!/bin/sh

APPDIR=$(dirname "$0")
java -Xms64m -Xmx10240m -Djna.nosys=true -Djava.library.path="$APPDIR:$APPDIR/lib" -cp "$APPDIR/lib/Hard_disk.jar:$APPDIR/lib/core.jar:$APPDIR/lib/jogl-all.jar:$APPDIR/lib/gluegen-rt.jar:$APPDIR/lib/jogl-all-natives-linux-i586.jar:$APPDIR/lib/gluegen-rt-natives-linux-i586.jar:$APPDIR/lib/itext.jar:$APPDIR/lib/pdf.jar" Hard_disk "$@"
